services:
  frontend:
    build: ./front-end
  postgres:
    image: postgres
    container_name: ai-videos-object-detection
    environment:
      POSTGRES_PASSWORD: postgres2024
      POSTGRES_USER: postgres
      POSTGRES_DB: ai-detection
    ports:
      - "5432:5432"
